# _agentbus — this file was generated by `agentbus install` and is removed by
# `agentbus uninstall`. Both of them look for this line: a file of this name
# without it is somebody's own and is never touched, so a copy you want to keep
# is a copy you rename.
#
# AGENTBUS_HOOK_VERSION=1
#
# The wrapper carries no logic. Devin hands it the hook payload as JSON on
# standard input and this passes it on untouched, so what an event means is
# decided by the binary named below and never here — which is why this file
# never has to be upgraded in step with anything. The same file is run on each
# of the six events registered for it and tells them apart by nothing at all:
# the payload says which one it was.
#
# Three rules govern what happens here, and all three come from where it runs:
# inside somebody's coding session, on every event their agent produces.
#
#   * It says nothing. Devin reads what a hook prints as an instruction, and
#     this program has no instructions for anybody's agent.
#   * It always succeeds. A failure raised here is a fault the user did not ask
#     for, in a session that had nothing to do with this program.
#   * It does nothing at all when the binary is not there. An installation left
#     behind by a binary that has since been removed is inert rather than
#     broken, which is what a machine with nothing listening looks like anyway.

# Where this machine keeps the binary the events are handed to. An absolute
# path, written in when this file was generated: the directory it lives in is
# not guaranteed to be on the PATH an agent runs its hooks with, and a command
# that cannot be found fails where nobody is looking.
binary=@BINARY@

if [ -x "$binary" ]; then
	"$binary" emit --agent devin >/dev/null 2>&1 || true
fi
exit 0
