// _agentbus — this file was generated by `agentbus install` and is removed by
// `agentbus uninstall`. Both of them look for this line: a file of this name
// without it is somebody's own and is never touched, so a copy you want to keep
// is a copy you rename.
//
// AGENTBUS_HOOK_VERSION=1
//
// The agent loads every extension in the directory this file sits in and calls
// the function exported below once, handing it something to subscribe to its
// own events with. A subscriber is called with the event and the context it
// happened in — there is no standard input to pass through — so what goes to
// the command is a small object of this file's own:
//
//     {"event": "<the name of the event that fired>",
//      "session_id": "<the session the agent named, if it named one>",
//      "mode": "<the interface that session is running under, where the agent
//               says>",
//      "has_ui": <whether the agent says somebody is looking at it>,
//      "cwd": "<the directory the agent is working in>"}
//
// The mapping for this agent is written against that shape, and it is the
// mapping — not this file — that decides what any of it means, including which
// sessions are worth reporting. That judgement is data: it lives with every
// other judgement about an event, and it changes by shipping a binary rather
// than by editing somebody's extension directory.
//
// The event object itself is not forwarded whole. Some of this agent's events
// carry the session's messages, which is the conversation so far and has no
// size worth relying on; handing that to a command on every turn would cost the
// user something on each one. What is taken from it instead is named above and
// nothing more.
//
// Three rules govern what happens here, and all three come from where it runs:
// inside somebody's coding session, on every event their agent produces.
//
//   * It never throws. An exception raised inside somebody's editor is a fault
//     they did not ask for and cannot act on.
//   * It never waits. The command is started and then let go of, so nothing the
//     user is waiting for is ever waiting for this.
//   * It never speaks. The command's output goes nowhere and its failure is
//     ignored, because losing one event is an acceptable outcome and
//     interrupting a session is not.
//
// @ts-nocheck

import { spawn } from "node:child_process";

// Where this machine keeps the binary the events are handed to. An absolute
// path, written in when the file was generated: the directory it lives in is
// not guaranteed to be on the `PATH` an agent runs its extensions with, and a
// command that cannot be found fails where nobody is looking.
const BINARY = "@BINARY@";

// The events this extension subscribes to.
//
// The one that says a session has begun, and the two that bracket the agent
// thinking. Nothing is subscribed to that nothing is waiting for: every one of
// these costs the user a process at the moment it fires.
const EVENTS = ["session_start", "agent_start", "agent_settled"];

// Hands one payload over and stops caring what becomes of it.
//
// The command and its arguments are passed separately rather than as a line for
// something else to split, so a path with a space or a quote in it reaches the
// binary as written. The child is released from the parent's accounting at
// once, which is what lets a session end without waiting for it, and both of
// the ways a spawn reports trouble asynchronously — a binary that is not there,
// a pipe closed before the payload was written — are listened for, because an
// unheard one of those is thrown at the session.
function handOver(payload) {
  try {
    const child = spawn(BINARY, ["emit", "--agent", "pi"], {
      stdio: ["pipe", "ignore", "ignore"],
      windowsHide: true,
    });
    child.on("error", () => {});
    child.stdin.on("error", () => {});
    child.unref();
    child.stdin.end(JSON.stringify(payload));
  } catch {
    // Deliberately nothing. There is no failure here worth a user's attention.
  }
}

// What the agent will say about the session an event happened in, if it says
// anything.
//
// Read through the context each time rather than remembered from the last
// event, because a session can be replaced underneath a running extension and a
// remembered id would then name the wrong one.
function session(context) {
  try {
    const id = context?.sessionManager?.getSessionId?.();
    return typeof id === "string" && id ? id : undefined;
  } catch {
    return undefined;
  }
}

// What the agent says about the interface it is running under.
//
// Two spellings because this agent's context has carried both: a name for the
// interface, and a flag saying whether there is one at all. Whichever it has is
// forwarded and the other is left out, and which of them means what is the
// mapping's business rather than this file's.
function surface(context) {
  const reported = {};
  try {
    if (typeof context?.mode === "string") {
      reported.mode = context.mode;
    }
    if (typeof context?.hasUI === "boolean") {
      reported.has_ui = context.hasUI;
    }
  } catch {
    // A context that cannot be read is a context that said nothing.
  }
  return reported;
}

export default function (agent) {
  for (const event of EVENTS) {
    agent.on(event, (_event, context) => {
      handOver({
        event,
        session_id: session(context),
        ...surface(context),
        cwd: process.cwd(),
      });
    });
  }
}
