# _agentbus — this file was generated by `agentbus install` and is removed by
# `agentbus uninstall`. Both of them look for this line: a file of this name
# without it is somebody's own and is never touched, so a copy you want to keep
# is a copy you rename.
#
# AGENTBUS_HOOK_VERSION=1
#
# The same wrapper as the one beside it, for a machine that runs its scripts by
# extension. It carries no logic: GitHub Copilot's command line hands it the
# hook payload as JSON on standard input and this passes it on untouched, so
# what an event means is decided by the binary named below and never here.
#
# Which of the two payload shapes arrives is decided by how the hook was
# registered rather than by anything here: the entry that runs this file names
# the event in the spelling whose payload carries `hook_event_name`, and the
# mapping the binary holds is written against that spelling.
#
# Three rules govern what happens here, and all three come from where it runs:
# inside somebody's coding session, on every event their agent produces.
#
#   * It says nothing. What a hook prints is read as an instruction, and this
#     program has no instructions for anybody's agent.
#   * It always succeeds. A failure raised here is a fault the user did not ask
#     for, in a session that had nothing to do with this program.
#   * It does nothing at all when the binary is not there. An installation left
#     behind by a binary that has since been removed is inert rather than
#     broken, which is what a machine with nothing listening looks like anyway.

# Where this machine keeps the binary the events are handed to. An absolute
# path, written in when this file was generated: the directory it lives in is
# not guaranteed to be on the PATH an agent runs its hooks with, and a command
# that cannot be found fails where nobody is looking.
$binary = @BINARY@

if (Test-Path -LiteralPath $binary -PathType Leaf) {
	try {
		# The payload is read here and handed over as the command's own input,
		# because a pipeline is how this shell passes one program's bytes to
		# another and there is nothing else to do with them.
		$payload = [Console]::In.ReadToEnd()
		$payload | & $binary emit --agent github-copilot *> $null
	} catch {
	}
}
exit 0
