# _agentbus — this file was generated by `agentbus install` and is removed by
# `agentbus uninstall`. Both of them look for this line: a file of this name
# without it is somebody's own and is never touched, so a copy you want to keep
# is a copy you rename.
#
# AGENTBUS_HOOK_VERSION=1
#
# The agent loads the directory this file is in as a plugin and calls `register`
# below once, handing it something to register callbacks with. A callback is
# called with keyword arguments and nothing else — there is no standard input to
# pass through — so what goes to the command is a small object of this file's
# own:
#
#     {"event": "<the name of the callback that fired>",
#      "session_id": "<the session the agent named, if it named one>",
#      "platform": "<the interface that session is running under>",
#      "cwd": "<the directory the agent is working in>"}
#
# The mapping for this agent is written against that shape, and it is the
# mapping — not this file — that decides what any of it means. Nothing is
# renamed, chosen between or left out on the way past: a field dropped here is
# one the far end can never get back, and which sessions are worth reporting is
# a judgement that belongs where every other judgement about an event belongs.
#
# Three rules govern what happens here, and all three come from where it runs:
# inside somebody's coding session, on every event their agent produces.
#
#   * It never raises. An exception raised inside somebody's session is a fault
#     they did not ask for and cannot act on.
#   * It never waits. The command is started and then let go of, so nothing the
#     user is waiting for is ever waiting for this.
#   * It never speaks. The command's output goes nowhere and its failure is
#     ignored, because losing one event is an acceptable outcome and
#     interrupting a session is not.

import json
import os
import subprocess

# Where this machine keeps the binary the events are handed to. An absolute
# path, written in when the file was generated: the directory it lives in is not
# guaranteed to be on the `PATH` an agent runs its plugins with, and a command
# that cannot be found fails where nobody is looking.
BINARY = "@BINARY@"

# The callbacks this plugin asks to be called on.
#
# The two that say a session has begun or begun again, and the one that fires
# before the agent thinks — which is the first thing heard about a session
# picked up again from the command line, where neither of the other two fires at
# all.
HOOKS = ("on_session_start", "on_session_reset", "pre_llm_call")


def _spawn_options():
    """What to start the command with, over and above the command itself.

    A Windows machine would otherwise put a console on the screen for the moment
    the command lives; every other machine has nothing to say here.
    """
    if os.name == "nt":
        return {"creationflags": subprocess.CREATE_NO_WINDOW}
    return {}


def _hand_over(payload):
    """Hands one payload over and stops caring what becomes of it.

    The command and its arguments are passed as a list rather than as a line for
    something else to split, so a path with a space or a quote in it reaches the
    binary as written. The child is never waited for, which is what lets a turn
    end without waiting for this, and a binary that is not there is the same
    quiet nothing as a machine with nothing listening.
    """
    try:
        child = subprocess.Popen(
            [BINARY, "emit", "--agent", "hermes"],
            stdin=subprocess.PIPE,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            **_spawn_options()
        )
    except Exception:
        return
    try:
        child.stdin.write(json.dumps(payload).encode("utf-8"))
        child.stdin.close()
    except Exception:
        # A pipe closed before the payload was written, which is the command
        # having gone away. There is nothing here worth a user's attention.
        pass


def _forward(event):
    """A callback reporting `event`, and what the agent said along with it."""

    def report(**fields):
        try:
            payload = {
                "event": event,
                "session_id": fields.get("session_id"),
                "platform": fields.get("platform"),
                "cwd": os.getcwd(),
            }
        except Exception:
            return
        _hand_over(payload)

    return report


def register(context):
    """Asks to be called on each of the events above."""
    for event in HOOKS:
        context.register_hook(event, _forward(event))
