# _agentbus — this file was generated by `agentbus install` and is removed by
# `agentbus uninstall`. Both of them look for this line: a file of this name
# without it is somebody's own and is never touched, so a copy you want to keep
# is a copy you rename.
#
# AGENTBUS_HOOK_VERSION=1
#
# The wrapper carries no logic. Antigravity hands it the hook payload as JSON on
# standard input and this passes it on untouched, so what an event means is
# decided by the binary named below and never here — which is why this file
# never has to be upgraded in step with anything.
#
# # Why this one is told which event it is about
#
# Alone among the agents here, Antigravity's payload does not say. It delivers
# one shape per event and expects whoever registered the hook to remember which
# event they registered for, so the entry that runs this passes the name and
# this passes it on. Nothing is added to the payload itself: the name travels
# beside it, and what is on standard input reaches the binary exactly as the
# agent wrote it.
#
# # Why this one answers
#
# Antigravity reads a hook's standard output as a list of steps to insert into
# the user's session, and an empty object is how that is spelled when there are
# none. This program has nothing to insert into anybody's session, so it says so
# explicitly on every path out of here rather than leaving the agent to make
# what it will of silence. That is the whole of what is printed.
#
# Two more rules govern what happens here, and both come from where it runs:
# inside somebody's coding session, on every event their agent produces.
#
#   * It always succeeds. A failure raised here is a fault the user did not ask
#     for, in a session that had nothing to do with this program.
#   * It does nothing at all when the binary is not there. An installation left
#     behind by a binary that has since been removed is inert rather than
#     broken, which is what a machine with nothing listening looks like anyway.

# Where this machine keeps the binary the events are handed to. An absolute
# path, written in when this file was generated: the directory it lives in is
# not guaranteed to be on the PATH an agent runs its hooks with, and a command
# that cannot be found fails where nobody is looking.
binary=@BINARY@

# Which of the agent's events this run is about, as the entry that runs this
# file was written to say. An empty one is a hook somebody has rewritten by
# hand, and a payload nothing can be said about is one to leave alone.
event=${1:-}

if [ -x "$binary" ] && [ -n "$event" ]; then
	"$binary" emit --agent antigravity --event "$event" >/dev/null 2>&1 || true
fi
printf '{}\n'
exit 0
